services:
  postgres:
    image: postgres:15
    ports:
      - "15432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    #      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bangrang
      TZ: Asia/Seoul  # 한국 표준시 설정
      POSTGRES_INITDB_ARGS: --encoding=UTF-8